spring:
  profiles:
    active:
      - initAccount
      - p6spy
    include:
      - dev
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000
        #one-indexed-parameters: true # paging 1

logging:
  level:
    p6spy: info
    org.hibernate.SQL: debug
    #org.hibernate.type: trace
